package session2.exercise.business_logic;

import session2.exercise.entity.Employee;
import session2.exercise.entity.Genre;

import java.util.List;

public class EmployeeManagement {

    // TODO 1: Print a report for all the employees.
    // Hint: the report line for one employee is generated by printReportLine() method
    public void printReportBody(List<Employee> employees) {
    }

    // TODO 2: Increase the salary of each employee
    public List<Employee> increaseSalary(List<Employee> employees, Double percentage) {
        return null;
    }

    // TODO 3: Filter employees by their genre
    public List<Employee> filterByGender(List<Employee> employees, Genre genre) {
        return null;
    }

    // TODO 4: Compute the salary average for the employees having a certain function
    // Hint: For the average, use a reduction function of the stream
    public Double getTotalSalaryByFunction(List<Employee> employees, String function) {
        return null;
    }

    private void printReportLine(Employee employee) {
        System.out.println(employee.getFirstName()
                + " "
                + employee.getLastName()
                + ", "
                + employee.getFunction()
                + " - "
                + employee.getSalary());
    }

    private double increaseAmount(Double amount, Double percentage) {
        return amount + amount * percentage;
    }
}
